// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: datachain/datastore/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe8615d92653abd, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe8615d92653abd, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryGetStoredChunkRequest defines the QueryGetStoredChunkRequest message.
type QueryGetStoredChunkRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetStoredChunkRequest) Reset()         { *m = QueryGetStoredChunkRequest{} }
func (m *QueryGetStoredChunkRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetStoredChunkRequest) ProtoMessage()    {}
func (*QueryGetStoredChunkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe8615d92653abd, []int{2}
}
func (m *QueryGetStoredChunkRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetStoredChunkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetStoredChunkRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetStoredChunkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetStoredChunkRequest.Merge(m, src)
}
func (m *QueryGetStoredChunkRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetStoredChunkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetStoredChunkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetStoredChunkRequest proto.InternalMessageInfo

func (m *QueryGetStoredChunkRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

// QueryGetStoredChunkResponse defines the QueryGetStoredChunkResponse message.
type QueryGetStoredChunkResponse struct {
	StoredChunk StoredChunk `protobuf:"bytes,1,opt,name=stored_chunk,json=storedChunk,proto3" json:"stored_chunk"`
}

func (m *QueryGetStoredChunkResponse) Reset()         { *m = QueryGetStoredChunkResponse{} }
func (m *QueryGetStoredChunkResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetStoredChunkResponse) ProtoMessage()    {}
func (*QueryGetStoredChunkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe8615d92653abd, []int{3}
}
func (m *QueryGetStoredChunkResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetStoredChunkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetStoredChunkResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetStoredChunkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetStoredChunkResponse.Merge(m, src)
}
func (m *QueryGetStoredChunkResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetStoredChunkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetStoredChunkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetStoredChunkResponse proto.InternalMessageInfo

func (m *QueryGetStoredChunkResponse) GetStoredChunk() StoredChunk {
	if m != nil {
		return m.StoredChunk
	}
	return StoredChunk{}
}

// QueryAllStoredChunkRequest defines the QueryAllStoredChunkRequest message.
type QueryAllStoredChunkRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllStoredChunkRequest) Reset()         { *m = QueryAllStoredChunkRequest{} }
func (m *QueryAllStoredChunkRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllStoredChunkRequest) ProtoMessage()    {}
func (*QueryAllStoredChunkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe8615d92653abd, []int{4}
}
func (m *QueryAllStoredChunkRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllStoredChunkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllStoredChunkRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllStoredChunkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllStoredChunkRequest.Merge(m, src)
}
func (m *QueryAllStoredChunkRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllStoredChunkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllStoredChunkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllStoredChunkRequest proto.InternalMessageInfo

func (m *QueryAllStoredChunkRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllStoredChunkResponse defines the QueryAllStoredChunkResponse message.
type QueryAllStoredChunkResponse struct {
	StoredChunk []StoredChunk       `protobuf:"bytes,1,rep,name=stored_chunk,json=storedChunk,proto3" json:"stored_chunk"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllStoredChunkResponse) Reset()         { *m = QueryAllStoredChunkResponse{} }
func (m *QueryAllStoredChunkResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllStoredChunkResponse) ProtoMessage()    {}
func (*QueryAllStoredChunkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe8615d92653abd, []int{5}
}
func (m *QueryAllStoredChunkResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllStoredChunkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllStoredChunkResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllStoredChunkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllStoredChunkResponse.Merge(m, src)
}
func (m *QueryAllStoredChunkResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllStoredChunkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllStoredChunkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllStoredChunkResponse proto.InternalMessageInfo

func (m *QueryAllStoredChunkResponse) GetStoredChunk() []StoredChunk {
	if m != nil {
		return m.StoredChunk
	}
	return nil
}

func (m *QueryAllStoredChunkResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "datachain.datastore.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "datachain.datastore.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGetStoredChunkRequest)(nil), "datachain.datastore.v1.QueryGetStoredChunkRequest")
	proto.RegisterType((*QueryGetStoredChunkResponse)(nil), "datachain.datastore.v1.QueryGetStoredChunkResponse")
	proto.RegisterType((*QueryAllStoredChunkRequest)(nil), "datachain.datastore.v1.QueryAllStoredChunkRequest")
	proto.RegisterType((*QueryAllStoredChunkResponse)(nil), "datachain.datastore.v1.QueryAllStoredChunkResponse")
}

func init() {
	proto.RegisterFile("datachain/datastore/v1/query.proto", fileDescriptor_6fe8615d92653abd)
}

var fileDescriptor_6fe8615d92653abd = []byte{
	// 518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x33, 0xad, 0x0d, 0x74, 0x2a, 0x8a, 0x63, 0x10, 0xd9, 0xca, 0x58, 0xa6, 0x12, 0x35,
	0x96, 0x19, 0x92, 0xea, 0x07, 0x68, 0x04, 0x7b, 0xe9, 0xa1, 0xae, 0x17, 0xf1, 0x22, 0x93, 0x64,
	0xd8, 0x2e, 0x4d, 0x66, 0xb6, 0x99, 0x49, 0x68, 0x11, 0x2f, 0xde, 0xbc, 0x09, 0x7e, 0x89, 0xde,
	0xf4, 0xe0, 0x87, 0xe8, 0xb1, 0xe0, 0xc5, 0x93, 0x48, 0x22, 0x78, 0xf5, 0x23, 0xc8, 0xce, 0x8c,
	0xcd, 0x46, 0x77, 0xdb, 0xa4, 0x97, 0xe5, 0xed, 0xf0, 0xfe, 0xef, 0xfd, 0xde, 0xbe, 0xff, 0x2c,
	0x24, 0x1d, 0x6e, 0x78, 0x7b, 0x8f, 0xc7, 0x92, 0xa5, 0x91, 0x36, 0xaa, 0x2f, 0xd8, 0xb0, 0xce,
	0x0e, 0x06, 0xa2, 0x7f, 0x44, 0x93, 0xbe, 0x32, 0x0a, 0xdd, 0x3a, 0xcb, 0xa1, 0x67, 0x39, 0x74,
	0x58, 0x0f, 0x6e, 0xf0, 0x5e, 0x2c, 0x15, 0xb3, 0x4f, 0x97, 0x1a, 0xd4, 0xda, 0x4a, 0xf7, 0x94,
	0x66, 0x2d, 0xae, 0x85, 0xab, 0xc1, 0x86, 0xf5, 0x96, 0x30, 0xbc, 0xce, 0x12, 0x1e, 0xc5, 0x92,
	0x9b, 0x58, 0x49, 0x9f, 0xbb, 0x5e, 0xd0, 0x3a, 0xe1, 0x7d, 0xde, 0xd3, 0x3e, 0xa9, 0x12, 0xa9,
	0x48, 0xd9, 0x90, 0xa5, 0x91, 0x3f, 0xbd, 0x13, 0x29, 0x15, 0x75, 0x05, 0xe3, 0x49, 0xcc, 0xb8,
	0x94, 0xca, 0xd8, 0xba, 0x7f, 0x35, 0x0f, 0x0b, 0x0a, 0xdb, 0xa0, 0xf3, 0xba, 0xbd, 0x37, 0x90,
	0xfb, 0x2e, 0x95, 0x54, 0x20, 0x7a, 0x9e, 0x52, 0xee, 0xda, 0x9e, 0xa1, 0x38, 0x18, 0x08, 0x6d,
	0xc8, 0x4b, 0x78, 0x73, 0xea, 0x54, 0x27, 0x4a, 0x6a, 0x81, 0xb6, 0x60, 0xd9, 0xb1, 0xdd, 0x06,
	0x6b, 0xe0, 0xc1, 0x4a, 0x03, 0xd3, 0xfc, 0x0f, 0x43, 0x9d, 0xae, 0xb9, 0x7c, 0xf2, 0xfd, 0x6e,
	0xe9, 0xf8, 0xd7, 0xe7, 0x1a, 0x08, 0xbd, 0x90, 0x34, 0x60, 0x60, 0x2b, 0x6f, 0x0b, 0xf3, 0xc2,
	0xd2, 0x3c, 0x4d, 0x61, 0x7c, 0x5f, 0x54, 0x81, 0x4b, 0xb1, 0xec, 0x88, 0x43, 0x5b, 0x7f, 0x39,
	0x74, 0x2f, 0x64, 0x1f, 0xae, 0xe6, 0x6a, 0x3c, 0xd5, 0x0e, 0xbc, 0x9a, 0x1d, 0xcc, 0xb3, 0xad,
	0x17, 0xb1, 0x65, 0x4a, 0x34, 0xaf, 0xa4, 0x80, 0xe1, 0x8a, 0x9e, 0x1c, 0x91, 0x8e, 0x07, 0xdc,
	0xea, 0x76, 0x73, 0x00, 0x9f, 0x41, 0x38, 0x59, 0xa3, 0xef, 0x54, 0xa5, 0x6e, 0xe7, 0x34, 0xdd,
	0x39, 0x75, 0xbe, 0xf1, 0x3b, 0xa7, 0xbb, 0x3c, 0x12, 0x5e, 0x1b, 0x66, 0x94, 0xe4, 0x0b, 0xf0,
	0x33, 0xfd, 0xdb, 0xa6, 0x70, 0xa6, 0xc5, 0xcb, 0xcf, 0x84, 0xb6, 0xa7, 0xa8, 0x17, 0x2c, 0xf5,
	0xfd, 0x0b, 0xa9, 0x1d, 0x4a, 0x16, 0xbb, 0xf1, 0x7b, 0x11, 0x2e, 0x59, 0x6c, 0xf4, 0x1e, 0xc0,
	0xb2, 0xdb, 0x32, 0xaa, 0x15, 0x51, 0xfd, 0x6f, 0xac, 0xe0, 0xd1, 0x4c, 0xb9, 0xae, 0x33, 0xa9,
	0xbe, 0xfb, 0xfa, 0xf3, 0xe3, 0xc2, 0x1a, 0xc2, 0xec, 0xdc, 0x8b, 0x82, 0x3e, 0x01, 0x78, 0x6d,
	0xda, 0x1b, 0xa8, 0x71, 0x6e, 0x9f, 0x5c, 0xf3, 0x05, 0x9b, 0x73, 0x69, 0x3c, 0xe3, 0x63, 0xcb,
	0x48, 0xd1, 0x06, 0x9b, 0xe1, 0xce, 0xb1, 0x37, 0xd6, 0xd0, 0x6f, 0xd1, 0x31, 0x80, 0xd7, 0x77,
	0x62, 0x3d, 0x07, 0x72, 0xae, 0x1d, 0x2f, 0x40, 0xce, 0xf7, 0x16, 0xd9, 0xb0, 0xc8, 0x55, 0x74,
	0x6f, 0x16, 0xe4, 0xe6, 0x93, 0x93, 0x11, 0x06, 0xa7, 0x23, 0x0c, 0x7e, 0x8c, 0x30, 0xf8, 0x30,
	0xc6, 0xa5, 0xd3, 0x31, 0x2e, 0x7d, 0x1b, 0xe3, 0xd2, 0xab, 0xd5, 0x89, 0xfc, 0x30, 0x53, 0xc0,
	0x1c, 0x25, 0x42, 0xb7, 0xca, 0xf6, 0xf7, 0xb2, 0xf9, 0x27, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xe2,
	0xcf, 0x52, 0x5f, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// ListStoredChunk Queries a list of StoredChunk items.
	GetStoredChunk(ctx context.Context, in *QueryGetStoredChunkRequest, opts ...grpc.CallOption) (*QueryGetStoredChunkResponse, error)
	// ListStoredChunk defines the ListStoredChunk RPC.
	ListStoredChunk(ctx context.Context, in *QueryAllStoredChunkRequest, opts ...grpc.CallOption) (*QueryAllStoredChunkResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/datachain.datastore.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetStoredChunk(ctx context.Context, in *QueryGetStoredChunkRequest, opts ...grpc.CallOption) (*QueryGetStoredChunkResponse, error) {
	out := new(QueryGetStoredChunkResponse)
	err := c.cc.Invoke(ctx, "/datachain.datastore.v1.Query/GetStoredChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListStoredChunk(ctx context.Context, in *QueryAllStoredChunkRequest, opts ...grpc.CallOption) (*QueryAllStoredChunkResponse, error) {
	out := new(QueryAllStoredChunkResponse)
	err := c.cc.Invoke(ctx, "/datachain.datastore.v1.Query/ListStoredChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// ListStoredChunk Queries a list of StoredChunk items.
	GetStoredChunk(context.Context, *QueryGetStoredChunkRequest) (*QueryGetStoredChunkResponse, error)
	// ListStoredChunk defines the ListStoredChunk RPC.
	ListStoredChunk(context.Context, *QueryAllStoredChunkRequest) (*QueryAllStoredChunkResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetStoredChunk(ctx context.Context, req *QueryGetStoredChunkRequest) (*QueryGetStoredChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStoredChunk not implemented")
}
func (*UnimplementedQueryServer) ListStoredChunk(ctx context.Context, req *QueryAllStoredChunkRequest) (*QueryAllStoredChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStoredChunk not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datachain.datastore.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetStoredChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetStoredChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetStoredChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datachain.datastore.v1.Query/GetStoredChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetStoredChunk(ctx, req.(*QueryGetStoredChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListStoredChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllStoredChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListStoredChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datachain.datastore.v1.Query/ListStoredChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListStoredChunk(ctx, req.(*QueryAllStoredChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "datachain.datastore.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetStoredChunk",
			Handler:    _Query_GetStoredChunk_Handler,
		},
		{
			MethodName: "ListStoredChunk",
			Handler:    _Query_ListStoredChunk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datachain/datastore/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetStoredChunkRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetStoredChunkRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetStoredChunkRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetStoredChunkResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetStoredChunkResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetStoredChunkResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.StoredChunk.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllStoredChunkRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllStoredChunkRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllStoredChunkRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllStoredChunkResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllStoredChunkResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllStoredChunkResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.StoredChunk) > 0 {
		for iNdEx := len(m.StoredChunk) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StoredChunk[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetStoredChunkRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetStoredChunkResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.StoredChunk.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllStoredChunkRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllStoredChunkResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.StoredChunk) > 0 {
		for _, e := range m.StoredChunk {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetStoredChunkRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetStoredChunkRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetStoredChunkRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetStoredChunkResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetStoredChunkResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetStoredChunkResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoredChunk", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StoredChunk.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllStoredChunkRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllStoredChunkRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllStoredChunkRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllStoredChunkResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllStoredChunkResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllStoredChunkResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoredChunk", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoredChunk = append(m.StoredChunk, StoredChunk{})
			if err := m.StoredChunk[len(m.StoredChunk)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
